\c quotes_dev;

INSERT INTO quotes (category, quote, author, source, language, year_quoted, is_favorite) VALUES
('LOVE','YOU KNOW YOU''RE IN LOVE WHEN YOU CAN''T FALL ASLEEP BECAUSE REALITY IS FINALLY BETTER THAN YOUR DREAMS','DR. SEUSS','MOVIE: THE LORAX','ENGLISH',1972,TRUE),

('LOVE','LOVE IS ALWAYS PATIENT AND KIND. IT IS NEVER RUDE OR SELFISH. IT DOES NOT TAKE OFFENSE AND IS NOT RESENTFUL. LOVE TAKES NO PLEASURE IN OTHER PEOPLE''S SINS, BUT DELIGHTS IN THE TRUTH. IT IS ALWAYS READY TO EXCUSE, TO TRUST, TO HOPE, AND TO ENDURE WHATEVER COMES','CORINTHIANS 1 13:4-7','THE HOLY BIBLE','HEBREW',53,TRUE),

('LOVE','LOVE ALL, TRUST A FEW, DO WRONG TO NONE','WILLIAM SHAKESPEARE','PLAY: ALL''S WELL THAT ENDS WELL','ENGLISH',1623,TRUE),

('INSPIRATIONAL','WE MAY ENCOUNTER MANY DEFEATS BUT WE MUST NOT BE DEFEATED','MAYA ANGELOU','BOOK: I KNOW WHY the CAGED BIRD SINGS','ENGLISH',1969,TRUE),

('INSPIRATIONAL','THE ONLY THING THAT FEELS BETTER THAN WINNING IS WINNING WHEN NOBODY THOUGHT YOU COULD','HANK AARON','MLB BOSTON BRAVES','ENGLISH',1952,TRUE),

('INSPIRATIONAL', 'IF YOUR ACTIONS INSPIRE OTHERS TO DREAM MORE, LEARN MORE, DO MORE AND BECOME MORE, YOU ARE A LEADER', 'JOHN QUINCY ADAMS', 'PAPER: AMERICAN REVOLUTION', 'ENGLISH', 1783, TRUE),

('DEATH', 'EVERYBODY IS GOING TO BE DEAD ONE DAY, JUST GIVE THEM TIME', 'NEIL DEGRASSI', 'TV SHOW: NOVA', 'ENGLISH', 2023, TRUE),

('DEATH', 'TO THE WELL-ORGANIZED MIND, DEATH IS BUT THE NEXT GREAT ADVENTURE', 'J.K ROWLING', 'BOOK: HARRY POTTER & THE SORCERER''S STONE', 'ENGLISH', 2015, TRUE),

('DEATH', 'IF A MAN HAS NOT DISCOVERED SOMETHING THAT HE WILL DIE FOR, HE ISN''T FIT TO LIVE', 'MLK, JR.', 'LOCATION: ALABAMA', 'ENGLISH', 1955, FALSE),

('LIFE', 'YOUR TIME IS LIMITED, DON''T WASTE IT LIVING SOMEONE ELSE''S LIFE', 'STEVE JOBS', 'MAGAZINE: THE ROLLING STONE', 'ENGLISH', 1994, TRUE),

('LIFE', 'LEARN AS IF YOU WILL LIVE FOREVER, LIVE LIKE YOU WILL DIE TOMORROW: "Tamē hammēśa māṭē jīvaśō tēma śīkhō, ēvī rītē jīvō kē jēma tamē kālē marī jaśō"', 'MAHATMA GANDHI', 'LOCATION: INDIA', 'GUJARATI', 1908, FALSE),

('LIFE', 'STAY AWAY FROM THOSE PEOPLE WHO TRY TO DISPARAGE YOUR AMBITIONS. SMALL MINDS WILL ALWAYS DO THAT, BUT GREAT MINDS WILL GIVE YOU A FEELING THAT YOU CAN BECOME GREAT TOO', 'MARK TWAIN', 'BOOK: ADVICE TO YOUTH', 'ENGLISH', 1882, TRUE),

('FUNNY', 'LIFE IS LIKE A BOX OF CHOCOLATES. YOU NEVER KNOW WHAT YOU''RE GONNA GET', 'FORREST GUMP', 'MOVIE: FORREST GUMP', 'ENGLISH', 1994, TRUE),

('FUNNY', 'I HAVE NO SPECIAL TALENT. I AM ONLY PASSIONATELY CURIOUS: "ICH HABE KEIN BESONDERES TALENT. ICH BIN NUR LEIDENSCHAFTLICH NEUGIERIG"', 'ALBERT EINSTEIN', 'NULL', 'GERMAN', 0, TRUE),

('FUNNY', 'THE OLDER YOU GET, THE BETTER YOU GET, UNLESS YOU''RE A BANANA', 'BETTY WHITE', 'SHOW: THE GOLDEN GIRLS', 'ENGLISH', 2016, TRUE),

('STRENGTH', 'ANYTHING WORTH HAVING, DOES NOT COME EASY: "TODO LO QUE VALE LA PENA, NO SALE FÁCIL"', 'UNKNOWN', 'LOCATION: THE BRONX', 'SPANISH', 0, TRUE),

('HOPE', 'HOPE IS THAT THING INSIDE US THAT INSIST, DESPITE ALL THE EVIDENCE, THAT SOMETHING BETTER AWAITS US IF WE REACH FOR IT, WORK FOR IT, AND FIGHT FOR IT', 'BARACK OBAMA', 'SPEECH: WHITE HOUSE', 'ENGLISH', 2012, TRUE),

('DETERMINATION', 'A DREAM DOESN''T BECOME REALITY THROUGH MAGIC; IT TAKES SWEAT, DETERMINATION, AND HARD WORK', 'COLIN POWELL', 'NULL', 'ENGLISH', 2007, TRUE),

('FRIENDSHIP', 'FRIENDSHIP IS THE HARDEST THING IN THE WORLD TO EXPLAIN', 'MUHAMMAD ALI', 'NULL', 'ENGLISH', 2016, TRUE),

('TRUST', 'TRUST IS THE GLUE TO LIFE. IT''S THE MOST ESSENTIAL INGREDIENT IN EFFECTIVE COMMUNICATION. IT''S THE FOUNDATIONAL PRINCIPLE THAT HOLDS ALL RELATIONSHIPS', 'STEPHEN COVEY', 'BOOK: FIRST THINGS FIRST', 'ENGLISH', 1995, TRUE);




-- //run on terminal to run this files/ restart new
-- //psql -U postgres -f db/schema.sql
-- //psql -U postgres -f db/seed.sql

